# -*- coding: utf-8 -*-
"""Internship day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibnYRvCXxYOO9grh7gwRjFaZW7nnXrk9
"""

List=[]
print("Blank list:")
print(List)
List=[10,20,30]
print("numbers:")
print(List)

My_tuple=()
print(My_tuple)
My_tuple=(1,2,3)
print(My_tuple)
My_tuple=(1,"hello",3)
print(My_tuple)

Dict={}
print("Empty Dictionary:")
print(Dict)
Dict[0]='geeks'
Dict[2]='for'
Dict[3]=1
print("in Dictionary after adding 3 elements:")
print(Dict)

A="pauline"
B="daisy"
print(A+B)
print(len(A))
print(len(B))