# -*- coding: utf-8 -*-
"""Internship day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uz8tg14ab_Omh0tNDjYGQCGkSUEsxTVv
"""

Name="daisy"
Age=19
CGPA=6.9
Placed=False
print("Student Name:",Name)
print("Age:",Age)
print("CGPA:",CGPA)
print("Placed:",Placed)
print(type(Name))
print(type(Age))
print(type(CGPA))
print(type(Placed))